; UART 8N1 transmitter, GPIO[0], LSB first.
; Each FIFO word contains three packed 10-bit UART frames and two idle-high bits.
.define BIT_DELAY 9
.pin 0
.program uart_tx

SET PINS, OUT
SET PINS, 1
PULL

.wrap_target
OUT PINS, 1 [BIT_DELAY]
OUT PINS, 1 [BIT_DELAY]
OUT PINS, 1 [BIT_DELAY]
OUT PINS, 1 [BIT_DELAY]
OUT PINS, 1 [BIT_DELAY]
OUT PINS, 1 [BIT_DELAY]
OUT PINS, 1 [BIT_DELAY]
OUT PINS, 1 [BIT_DELAY]
OUT PINS, 1 [BIT_DELAY]
OUT PINS, 1 [BIT_DELAY]
OUT PINS, 1 [BIT_DELAY]
OUT PINS, 1 [BIT_DELAY]
OUT PINS, 1 [BIT_DELAY]
OUT PINS, 1 [BIT_DELAY]
OUT PINS, 1 [BIT_DELAY]
OUT PINS, 1 [BIT_DELAY]
OUT PINS, 1 [BIT_DELAY]
OUT PINS, 1 [BIT_DELAY]
OUT PINS, 1 [BIT_DELAY]
OUT PINS, 1 [BIT_DELAY]
OUT PINS, 1 [BIT_DELAY]
OUT PINS, 1 [BIT_DELAY]
OUT PINS, 1 [BIT_DELAY]
OUT PINS, 1 [BIT_DELAY]
OUT PINS, 1 [BIT_DELAY]
OUT PINS, 1 [BIT_DELAY]
OUT PINS, 1 [BIT_DELAY]
OUT PINS, 1 [BIT_DELAY]
OUT PINS, 1 [BIT_DELAY]
OUT PINS, 1 [BIT_DELAY]
OUT PINS, 1 [BIT_DELAY]
OUT PINS, 1 [BIT_DELAY]
PULL
.wrap
