; UART 8N1 receiver, GPIO[1], LSB first.
.define BIT_DELAY 9
.define START_TO_BIT0_DELAY 14
.pin 1
.program uart_rx

SET PINS, IN

.wrap_target
WAIT 0 PIN
NOP [START_TO_BIT0_DELAY]
IN PINS, 1 [BIT_DELAY]
IN PINS, 1 [BIT_DELAY]
IN PINS, 1 [BIT_DELAY]
IN PINS, 1 [BIT_DELAY]
IN PINS, 1 [BIT_DELAY]
IN PINS, 1 [BIT_DELAY]
IN PINS, 1 [BIT_DELAY]
IN PINS, 1 [BIT_DELAY]
PUSH
WAIT 1 PIN
.wrap
